### ISSUE TITLE
The bot does not find the exefile path

### ISSUE THREAD

**Issue by Binopsy** [botengine-de/A-Bot#10]
I started the bot, but it doesn't find the path even when the Eve client is open.
(However, it does find the launcher)

Actual bot (trying) to use : A-bot latest release 2018-04-04

After that I tried and downloaded Sanderling.exe version 2019-05-13 (mining and autotraveling). This one does find the eve client.

So, question is , why does A-bot not find my eve client although the Sanderling v2019 does?

**Comment by Viir** [comment]
Thank you, @Binopsy for sharing your findings. Maybe there were changes in the part of Sanderling which does the finding of the EVE client process to adapt to changes in the EVE Online client. In this case, maybe A-Bot can be updated to find it as well by switching to the newer version of Sanderling. I see Sanderling integrated in A-Bot at least in https://github.com/botengine-de/A-Bot/tree/2fc03f1345955ad068da17b862f05cee8daab195/lib

For (future) perspective, it looks like A-Bot is going to be obsoleted in 2019 anyway, because of the introduction of better options for anomaly ratting.

**Comment by tannenheuser** [comment]
I just started looking at bots do assist me with some basic Ishtar/Domi ratting for low profile income, but I have the exact same issue as the other comment here. 

In your previous comment you mention that this might be made obsolete in 2019, due to other alternatives. Where do you suggest I start looking? I find it hard to know where to start.

**Comment by Viir** [comment]
> I have the exact same issue as the other comment here.

In the meantime, we discovered you can fix this in the EVE Online client settings: https://github.com/Viir/bots/blob/21ca6ece5d7751769b8fad7d5b24f434530a58cc/guide/eve-online/how-to-automate-traveling-in-eve-online-using-a-warp-to-0-autopilot.md
The relevant part from this guide for you is:

>  Make sure that the setting Run clients with 64 bit is disabled for the EVE Online client.

> In your previous comment you mention that this might be made obsolete in 2019, due to other alternatives.

Yes, it still looks like we will have something better than A-Bot for anomaly ratting. But the new anomaly ratting bot will not be ready before December. At the current stage, the new anomaly ratting bot is only of interest for developers.

**Comment by Viir** [comment]
> I have the exact same issue as the other comment here.

I recommend to try a version which includes the newer Sanderling assemblies. We had quite some people working on A-Bot more recently, so there are probably people who are familiar with the process or already have such an updated version. You can see the network at https://github.com/botengine-de/A-Bot/network/members

> In your previous comment you mention that this might be made obsolete in 2019, due to other alternatives.

The new anomaly ratting bot is work-in-progress. At the current stage, it is only of interest to developers. For now, A-Bot is still easier to set up. The new anomaly ratting bot will not be ready before December.

> Where do you suggest I start looking? I find it hard to know where to start.

Besides the specific solution above: For the progress on EVE Online bots in general, there are two sources to get updates:

> https://github.com/Viir/bots/commits/master
> https://forum.botengine.org/t/botengine-devlog/2183/

**Comment by Viir** [comment]
We found an anomaly ratting bot that works with 64-bit EVE Online clients and is easier to customize. I updated the repository for this new bot.

**Comment by Viir** [comment]
There is now an easy way to find the latest version of the EVE Online ratting bot.

The following link is updated frequently updated and automatically redirects to the newest version:
https://to.botlab.org/guide/app/eve-online-combat-anomaly-bot

That guide explains how to run the bot and links the current source codes for development and relevant artifacts.
